---
version: "2.1"
services:
  transmission:
    image: lscr.io/linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
      - USER=albertofv #optional
      - PASS=S3cr3t0 #optional
#      - WHITELIST=iplist #optional
#      - HOST_WHITELIST=dnsnane list #optional
    volumes:
      - ./config:/config
      - /home/albertofv/crucial/jellyfin/media/peliculas/HDOlimpo/downloads
      - ./watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped